name: SDMX-DL-UI DEPLOYMENT

on:
  push:
    tags:
      - 0.*
      - 1.*

env:
  configuration: Release

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install .NET
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: 6.0.x

      - name: NuGet restore
        run: dotnet restore
        working-directory: src

      - name: Build
        run: dotnet build --configuration=Release --verbosity=minimal --no-restore
        working-directory: src

      - name: Unit tests
        run: dotnet test --configuration=Release --verbosity=minimal --no-build
        working-directory: src

  pack-and-publish:
    needs: build-and-test
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install .NET
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: 6.0.x

      - uses: little-core-labs/get-git-tag@v3.0.1
        id: tagname

      - name: Pack
        run: dotnet pack -p:PackageVersion=${{ steps.tagName.outputs.tag }} --configuration=Release --verbosity=minimal
        working-directory: src

      - name: Push
        run: dotnet nuget push **/sdmx-dl-engine/nupkg/*.nupkg -k ${{secrets.NUGET_SDMX_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate